/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/maintenance/v1alpha1"
	scheme "kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WindowsGetter has a method to return a WindowInterface.
// A group's client should implement this interface.
type WindowsGetter interface {
	Windows(namespace string) WindowInterface
}

// WindowInterface has methods to work with Window resources.
type WindowInterface interface {
	Create(ctx context.Context, window *v1alpha1.Window, opts v1.CreateOptions) (*v1alpha1.Window, error)
	Update(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (*v1alpha1.Window, error)
	UpdateStatus(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (*v1alpha1.Window, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Window, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WindowList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Window, err error)
	WindowExpansion
}

// windows implements WindowInterface
type windows struct {
	client rest.Interface
	ns     string
}

// newWindows returns a Windows
func newWindows(c *MaintenanceV1alpha1Client, namespace string) *windows {
	return &windows{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the window, and returns the corresponding window object, and an error if there is any.
func (c *windows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Window, err error) {
	result = &v1alpha1.Window{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("windows").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Windows that match those selectors.
func (c *windows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WindowList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WindowList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("windows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested windows.
func (c *windows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("windows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a window and creates it.  Returns the server's representation of the window, and an error, if there is any.
func (c *windows) Create(ctx context.Context, window *v1alpha1.Window, opts v1.CreateOptions) (result *v1alpha1.Window, err error) {
	result = &v1alpha1.Window{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("windows").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(window).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a window and updates it. Returns the server's representation of the window, and an error, if there is any.
func (c *windows) Update(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (result *v1alpha1.Window, err error) {
	result = &v1alpha1.Window{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("windows").
		Name(window.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(window).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *windows) UpdateStatus(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (result *v1alpha1.Window, err error) {
	result = &v1alpha1.Window{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("windows").
		Name(window.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(window).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the window and deletes it. Returns an error if one occurs.
func (c *windows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("windows").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *windows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("windows").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched window.
func (c *windows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Window, err error) {
	result = &v1alpha1.Window{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("windows").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
