/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IntegrationAppDynamicsListerExpansion allows custom methods to be added to
// IntegrationAppDynamicsLister.
type IntegrationAppDynamicsListerExpansion interface{}

// IntegrationAppDynamicsNamespaceListerExpansion allows custom methods to be added to
// IntegrationAppDynamicsNamespaceLister.
type IntegrationAppDynamicsNamespaceListerExpansion interface{}

// IntegrationAwsExternalIDListerExpansion allows custom methods to be added to
// IntegrationAwsExternalIDLister.
type IntegrationAwsExternalIDListerExpansion interface{}

// IntegrationAwsExternalIDNamespaceListerExpansion allows custom methods to be added to
// IntegrationAwsExternalIDNamespaceLister.
type IntegrationAwsExternalIDNamespaceListerExpansion interface{}

// IntegrationAzureListerExpansion allows custom methods to be added to
// IntegrationAzureLister.
type IntegrationAzureListerExpansion interface{}

// IntegrationAzureNamespaceListerExpansion allows custom methods to be added to
// IntegrationAzureNamespaceLister.
type IntegrationAzureNamespaceListerExpansion interface{}

// IntegrationAzureActivityLogListerExpansion allows custom methods to be added to
// IntegrationAzureActivityLogLister.
type IntegrationAzureActivityLogListerExpansion interface{}

// IntegrationAzureActivityLogNamespaceListerExpansion allows custom methods to be added to
// IntegrationAzureActivityLogNamespaceLister.
type IntegrationAzureActivityLogNamespaceListerExpansion interface{}

// IntegrationCloudtrailListerExpansion allows custom methods to be added to
// IntegrationCloudtrailLister.
type IntegrationCloudtrailListerExpansion interface{}

// IntegrationCloudtrailNamespaceListerExpansion allows custom methods to be added to
// IntegrationCloudtrailNamespaceLister.
type IntegrationCloudtrailNamespaceListerExpansion interface{}

// IntegrationCloudwatchListerExpansion allows custom methods to be added to
// IntegrationCloudwatchLister.
type IntegrationCloudwatchListerExpansion interface{}

// IntegrationCloudwatchNamespaceListerExpansion allows custom methods to be added to
// IntegrationCloudwatchNamespaceLister.
type IntegrationCloudwatchNamespaceListerExpansion interface{}

// IntegrationEc2ListerExpansion allows custom methods to be added to
// IntegrationEc2Lister.
type IntegrationEc2ListerExpansion interface{}

// IntegrationEc2NamespaceListerExpansion allows custom methods to be added to
// IntegrationEc2NamespaceLister.
type IntegrationEc2NamespaceListerExpansion interface{}

// IntegrationGcpListerExpansion allows custom methods to be added to
// IntegrationGcpLister.
type IntegrationGcpListerExpansion interface{}

// IntegrationGcpNamespaceListerExpansion allows custom methods to be added to
// IntegrationGcpNamespaceLister.
type IntegrationGcpNamespaceListerExpansion interface{}

// IntegrationGcpBillingListerExpansion allows custom methods to be added to
// IntegrationGcpBillingLister.
type IntegrationGcpBillingListerExpansion interface{}

// IntegrationGcpBillingNamespaceListerExpansion allows custom methods to be added to
// IntegrationGcpBillingNamespaceLister.
type IntegrationGcpBillingNamespaceListerExpansion interface{}

// IntegrationNewrelicListerExpansion allows custom methods to be added to
// IntegrationNewrelicLister.
type IntegrationNewrelicListerExpansion interface{}

// IntegrationNewrelicNamespaceListerExpansion allows custom methods to be added to
// IntegrationNewrelicNamespaceLister.
type IntegrationNewrelicNamespaceListerExpansion interface{}

// IntegrationTeslaListerExpansion allows custom methods to be added to
// IntegrationTeslaLister.
type IntegrationTeslaListerExpansion interface{}

// IntegrationTeslaNamespaceListerExpansion allows custom methods to be added to
// IntegrationTeslaNamespaceLister.
type IntegrationTeslaNamespaceListerExpansion interface{}
