/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	"kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type CloudV1alpha1Interface interface {
	RESTClient() rest.Interface
	IntegrationAppDynamicsesGetter
	IntegrationAwsExternalIDsGetter
	IntegrationAzuresGetter
	IntegrationAzureActivityLogsGetter
	IntegrationCloudtrailsGetter
	IntegrationCloudwatchesGetter
	IntegrationEc2sGetter
	IntegrationGcpsGetter
	IntegrationGcpBillingsGetter
	IntegrationNewrelicsGetter
	IntegrationTeslasGetter
}

// CloudV1alpha1Client is used to interact with features provided by the cloud.wavefront.kubeform.com group.
type CloudV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CloudV1alpha1Client) IntegrationAppDynamicses(namespace string) IntegrationAppDynamicsInterface {
	return newIntegrationAppDynamicses(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationAwsExternalIDs(namespace string) IntegrationAwsExternalIDInterface {
	return newIntegrationAwsExternalIDs(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationAzures(namespace string) IntegrationAzureInterface {
	return newIntegrationAzures(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationAzureActivityLogs(namespace string) IntegrationAzureActivityLogInterface {
	return newIntegrationAzureActivityLogs(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationCloudtrails(namespace string) IntegrationCloudtrailInterface {
	return newIntegrationCloudtrails(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationCloudwatches(namespace string) IntegrationCloudwatchInterface {
	return newIntegrationCloudwatches(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationEc2s(namespace string) IntegrationEc2Interface {
	return newIntegrationEc2s(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationGcps(namespace string) IntegrationGcpInterface {
	return newIntegrationGcps(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationGcpBillings(namespace string) IntegrationGcpBillingInterface {
	return newIntegrationGcpBillings(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationNewrelics(namespace string) IntegrationNewrelicInterface {
	return newIntegrationNewrelics(c, namespace)
}

func (c *CloudV1alpha1Client) IntegrationTeslas(namespace string) IntegrationTeslaInterface {
	return newIntegrationTeslas(c, namespace)
}

// NewForConfig creates a new CloudV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CloudV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CloudV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CloudV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CloudV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CloudV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CloudV1alpha1Client {
	return &CloudV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CloudV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
