/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type IntegrationAppDynamicsExpansion interface{}

type IntegrationAwsExternalIDExpansion interface{}

type IntegrationAzureExpansion interface{}

type IntegrationAzureActivityLogExpansion interface{}

type IntegrationCloudtrailExpansion interface{}

type IntegrationCloudwatchExpansion interface{}

type IntegrationEc2Expansion interface{}

type IntegrationGcpExpansion interface{}

type IntegrationGcpBillingExpansion interface{}

type IntegrationNewrelicExpansion interface{}

type IntegrationTeslaExpansion interface{}
