/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	scheme "kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IntegrationGcpBillingsGetter has a method to return a IntegrationGcpBillingInterface.
// A group's client should implement this interface.
type IntegrationGcpBillingsGetter interface {
	IntegrationGcpBillings(namespace string) IntegrationGcpBillingInterface
}

// IntegrationGcpBillingInterface has methods to work with IntegrationGcpBilling resources.
type IntegrationGcpBillingInterface interface {
	Create(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.CreateOptions) (*v1alpha1.IntegrationGcpBilling, error)
	Update(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (*v1alpha1.IntegrationGcpBilling, error)
	UpdateStatus(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (*v1alpha1.IntegrationGcpBilling, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IntegrationGcpBilling, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IntegrationGcpBillingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationGcpBilling, err error)
	IntegrationGcpBillingExpansion
}

// integrationGcpBillings implements IntegrationGcpBillingInterface
type integrationGcpBillings struct {
	client rest.Interface
	ns     string
}

// newIntegrationGcpBillings returns a IntegrationGcpBillings
func newIntegrationGcpBillings(c *CloudV1alpha1Client, namespace string) *integrationGcpBillings {
	return &integrationGcpBillings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationGcpBilling, and returns the corresponding integrationGcpBilling object, and an error if there is any.
func (c *integrationGcpBillings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	result = &v1alpha1.IntegrationGcpBilling{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationGcpBillings that match those selectors.
func (c *integrationGcpBillings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationGcpBillingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationGcpBillingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationGcpBillings.
func (c *integrationGcpBillings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a integrationGcpBilling and creates it.  Returns the server's representation of the integrationGcpBilling, and an error, if there is any.
func (c *integrationGcpBillings) Create(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.CreateOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	result = &v1alpha1.IntegrationGcpBilling{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationGcpBilling).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a integrationGcpBilling and updates it. Returns the server's representation of the integrationGcpBilling, and an error, if there is any.
func (c *integrationGcpBillings) Update(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	result = &v1alpha1.IntegrationGcpBilling{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		Name(integrationGcpBilling.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationGcpBilling).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *integrationGcpBillings) UpdateStatus(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	result = &v1alpha1.IntegrationGcpBilling{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		Name(integrationGcpBilling.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationGcpBilling).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the integrationGcpBilling and deletes it. Returns an error if one occurs.
func (c *integrationGcpBillings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationGcpBillings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched integrationGcpBilling.
func (c *integrationGcpBillings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationGcpBilling, err error) {
	result = &v1alpha1.IntegrationGcpBilling{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationgcpbillings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
