/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	scheme "kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IntegrationAppDynamicsesGetter has a method to return a IntegrationAppDynamicsInterface.
// A group's client should implement this interface.
type IntegrationAppDynamicsesGetter interface {
	IntegrationAppDynamicses(namespace string) IntegrationAppDynamicsInterface
}

// IntegrationAppDynamicsInterface has methods to work with IntegrationAppDynamics resources.
type IntegrationAppDynamicsInterface interface {
	Create(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.CreateOptions) (*v1alpha1.IntegrationAppDynamics, error)
	Update(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.UpdateOptions) (*v1alpha1.IntegrationAppDynamics, error)
	UpdateStatus(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.UpdateOptions) (*v1alpha1.IntegrationAppDynamics, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IntegrationAppDynamics, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IntegrationAppDynamicsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationAppDynamics, err error)
	IntegrationAppDynamicsExpansion
}

// integrationAppDynamicses implements IntegrationAppDynamicsInterface
type integrationAppDynamicses struct {
	client rest.Interface
	ns     string
}

// newIntegrationAppDynamicses returns a IntegrationAppDynamicses
func newIntegrationAppDynamicses(c *CloudV1alpha1Client, namespace string) *integrationAppDynamicses {
	return &integrationAppDynamicses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationAppDynamics, and returns the corresponding integrationAppDynamics object, and an error if there is any.
func (c *integrationAppDynamicses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationAppDynamics, err error) {
	result = &v1alpha1.IntegrationAppDynamics{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationAppDynamicses that match those selectors.
func (c *integrationAppDynamicses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationAppDynamicsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationAppDynamicsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationAppDynamicses.
func (c *integrationAppDynamicses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a integrationAppDynamics and creates it.  Returns the server's representation of the integrationAppDynamics, and an error, if there is any.
func (c *integrationAppDynamicses) Create(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.CreateOptions) (result *v1alpha1.IntegrationAppDynamics, err error) {
	result = &v1alpha1.IntegrationAppDynamics{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAppDynamics).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a integrationAppDynamics and updates it. Returns the server's representation of the integrationAppDynamics, and an error, if there is any.
func (c *integrationAppDynamicses) Update(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.UpdateOptions) (result *v1alpha1.IntegrationAppDynamics, err error) {
	result = &v1alpha1.IntegrationAppDynamics{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		Name(integrationAppDynamics.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAppDynamics).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *integrationAppDynamicses) UpdateStatus(ctx context.Context, integrationAppDynamics *v1alpha1.IntegrationAppDynamics, opts v1.UpdateOptions) (result *v1alpha1.IntegrationAppDynamics, err error) {
	result = &v1alpha1.IntegrationAppDynamics{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		Name(integrationAppDynamics.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAppDynamics).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the integrationAppDynamics and deletes it. Returns an error if one occurs.
func (c *integrationAppDynamicses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationAppDynamicses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched integrationAppDynamics.
func (c *integrationAppDynamicses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationAppDynamics, err error) {
	result = &v1alpha1.IntegrationAppDynamics{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationappdynamicses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
