/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	scheme "kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IntegrationAzuresGetter has a method to return a IntegrationAzureInterface.
// A group's client should implement this interface.
type IntegrationAzuresGetter interface {
	IntegrationAzures(namespace string) IntegrationAzureInterface
}

// IntegrationAzureInterface has methods to work with IntegrationAzure resources.
type IntegrationAzureInterface interface {
	Create(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.CreateOptions) (*v1alpha1.IntegrationAzure, error)
	Update(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.UpdateOptions) (*v1alpha1.IntegrationAzure, error)
	UpdateStatus(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.UpdateOptions) (*v1alpha1.IntegrationAzure, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IntegrationAzure, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IntegrationAzureList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationAzure, err error)
	IntegrationAzureExpansion
}

// integrationAzures implements IntegrationAzureInterface
type integrationAzures struct {
	client rest.Interface
	ns     string
}

// newIntegrationAzures returns a IntegrationAzures
func newIntegrationAzures(c *CloudV1alpha1Client, namespace string) *integrationAzures {
	return &integrationAzures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationAzure, and returns the corresponding integrationAzure object, and an error if there is any.
func (c *integrationAzures) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationAzure, err error) {
	result = &v1alpha1.IntegrationAzure{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationazures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationAzures that match those selectors.
func (c *integrationAzures) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationAzureList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationAzureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationazures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationAzures.
func (c *integrationAzures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationazures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a integrationAzure and creates it.  Returns the server's representation of the integrationAzure, and an error, if there is any.
func (c *integrationAzures) Create(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.CreateOptions) (result *v1alpha1.IntegrationAzure, err error) {
	result = &v1alpha1.IntegrationAzure{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationazures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAzure).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a integrationAzure and updates it. Returns the server's representation of the integrationAzure, and an error, if there is any.
func (c *integrationAzures) Update(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.UpdateOptions) (result *v1alpha1.IntegrationAzure, err error) {
	result = &v1alpha1.IntegrationAzure{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationazures").
		Name(integrationAzure.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAzure).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *integrationAzures) UpdateStatus(ctx context.Context, integrationAzure *v1alpha1.IntegrationAzure, opts v1.UpdateOptions) (result *v1alpha1.IntegrationAzure, err error) {
	result = &v1alpha1.IntegrationAzure{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationazures").
		Name(integrationAzure.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationAzure).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the integrationAzure and deletes it. Returns an error if one occurs.
func (c *integrationAzures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationazures").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationAzures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationazures").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched integrationAzure.
func (c *integrationAzures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationAzure, err error) {
	result = &v1alpha1.IntegrationAzure{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationazures").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
