/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	scheme "kubeform.dev/provider-wavefront-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IntegrationNewrelicsGetter has a method to return a IntegrationNewrelicInterface.
// A group's client should implement this interface.
type IntegrationNewrelicsGetter interface {
	IntegrationNewrelics(namespace string) IntegrationNewrelicInterface
}

// IntegrationNewrelicInterface has methods to work with IntegrationNewrelic resources.
type IntegrationNewrelicInterface interface {
	Create(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.CreateOptions) (*v1alpha1.IntegrationNewrelic, error)
	Update(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (*v1alpha1.IntegrationNewrelic, error)
	UpdateStatus(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (*v1alpha1.IntegrationNewrelic, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IntegrationNewrelic, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IntegrationNewrelicList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationNewrelic, err error)
	IntegrationNewrelicExpansion
}

// integrationNewrelics implements IntegrationNewrelicInterface
type integrationNewrelics struct {
	client rest.Interface
	ns     string
}

// newIntegrationNewrelics returns a IntegrationNewrelics
func newIntegrationNewrelics(c *CloudV1alpha1Client, namespace string) *integrationNewrelics {
	return &integrationNewrelics{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationNewrelic, and returns the corresponding integrationNewrelic object, and an error if there is any.
func (c *integrationNewrelics) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	result = &v1alpha1.IntegrationNewrelic{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationNewrelics that match those selectors.
func (c *integrationNewrelics) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationNewrelicList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationNewrelicList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationNewrelics.
func (c *integrationNewrelics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a integrationNewrelic and creates it.  Returns the server's representation of the integrationNewrelic, and an error, if there is any.
func (c *integrationNewrelics) Create(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.CreateOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	result = &v1alpha1.IntegrationNewrelic{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationNewrelic).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a integrationNewrelic and updates it. Returns the server's representation of the integrationNewrelic, and an error, if there is any.
func (c *integrationNewrelics) Update(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	result = &v1alpha1.IntegrationNewrelic{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		Name(integrationNewrelic.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationNewrelic).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *integrationNewrelics) UpdateStatus(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	result = &v1alpha1.IntegrationNewrelic{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		Name(integrationNewrelic.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationNewrelic).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the integrationNewrelic and deletes it. Returns an error if one occurs.
func (c *integrationNewrelics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationNewrelics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationnewrelics").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched integrationNewrelic.
func (c *integrationNewrelics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationNewrelic, err error) {
	result = &v1alpha1.IntegrationNewrelic{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationnewrelics").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
