/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/maintenance/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWindows implements WindowInterface
type FakeWindows struct {
	Fake *FakeMaintenanceV1alpha1
	ns   string
}

var windowsResource = schema.GroupVersionResource{Group: "maintenance.wavefront.kubeform.com", Version: "v1alpha1", Resource: "windows"}

var windowsKind = schema.GroupVersionKind{Group: "maintenance.wavefront.kubeform.com", Version: "v1alpha1", Kind: "Window"}

// Get takes name of the window, and returns the corresponding window object, and an error if there is any.
func (c *FakeWindows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Window, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(windowsResource, c.ns, name), &v1alpha1.Window{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Window), err
}

// List takes label and field selectors, and returns the list of Windows that match those selectors.
func (c *FakeWindows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WindowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(windowsResource, windowsKind, c.ns, opts), &v1alpha1.WindowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WindowList{ListMeta: obj.(*v1alpha1.WindowList).ListMeta}
	for _, item := range obj.(*v1alpha1.WindowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested windows.
func (c *FakeWindows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(windowsResource, c.ns, opts))

}

// Create takes the representation of a window and creates it.  Returns the server's representation of the window, and an error, if there is any.
func (c *FakeWindows) Create(ctx context.Context, window *v1alpha1.Window, opts v1.CreateOptions) (result *v1alpha1.Window, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(windowsResource, c.ns, window), &v1alpha1.Window{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Window), err
}

// Update takes the representation of a window and updates it. Returns the server's representation of the window, and an error, if there is any.
func (c *FakeWindows) Update(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (result *v1alpha1.Window, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(windowsResource, c.ns, window), &v1alpha1.Window{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Window), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWindows) UpdateStatus(ctx context.Context, window *v1alpha1.Window, opts v1.UpdateOptions) (*v1alpha1.Window, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(windowsResource, "status", c.ns, window), &v1alpha1.Window{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Window), err
}

// Delete takes name of the window and deletes it. Returns an error if one occurs.
func (c *FakeWindows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(windowsResource, c.ns, name), &v1alpha1.Window{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWindows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(windowsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WindowList{})
	return err
}

// Patch applies the patch and returns the patched window.
func (c *FakeWindows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Window, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(windowsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Window{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Window), err
}
