/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationCloudwatches implements IntegrationCloudwatchInterface
type FakeIntegrationCloudwatches struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationcloudwatchesResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationcloudwatches"}

var integrationcloudwatchesKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationCloudwatch"}

// Get takes name of the integrationCloudwatch, and returns the corresponding integrationCloudwatch object, and an error if there is any.
func (c *FakeIntegrationCloudwatches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationCloudwatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationcloudwatchesResource, c.ns, name), &v1alpha1.IntegrationCloudwatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudwatch), err
}

// List takes label and field selectors, and returns the list of IntegrationCloudwatches that match those selectors.
func (c *FakeIntegrationCloudwatches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationCloudwatchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationcloudwatchesResource, integrationcloudwatchesKind, c.ns, opts), &v1alpha1.IntegrationCloudwatchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationCloudwatchList{ListMeta: obj.(*v1alpha1.IntegrationCloudwatchList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationCloudwatchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationCloudwatches.
func (c *FakeIntegrationCloudwatches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationcloudwatchesResource, c.ns, opts))

}

// Create takes the representation of a integrationCloudwatch and creates it.  Returns the server's representation of the integrationCloudwatch, and an error, if there is any.
func (c *FakeIntegrationCloudwatches) Create(ctx context.Context, integrationCloudwatch *v1alpha1.IntegrationCloudwatch, opts v1.CreateOptions) (result *v1alpha1.IntegrationCloudwatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationcloudwatchesResource, c.ns, integrationCloudwatch), &v1alpha1.IntegrationCloudwatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudwatch), err
}

// Update takes the representation of a integrationCloudwatch and updates it. Returns the server's representation of the integrationCloudwatch, and an error, if there is any.
func (c *FakeIntegrationCloudwatches) Update(ctx context.Context, integrationCloudwatch *v1alpha1.IntegrationCloudwatch, opts v1.UpdateOptions) (result *v1alpha1.IntegrationCloudwatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationcloudwatchesResource, c.ns, integrationCloudwatch), &v1alpha1.IntegrationCloudwatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudwatch), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationCloudwatches) UpdateStatus(ctx context.Context, integrationCloudwatch *v1alpha1.IntegrationCloudwatch, opts v1.UpdateOptions) (*v1alpha1.IntegrationCloudwatch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationcloudwatchesResource, "status", c.ns, integrationCloudwatch), &v1alpha1.IntegrationCloudwatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudwatch), err
}

// Delete takes name of the integrationCloudwatch and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationCloudwatches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationcloudwatchesResource, c.ns, name), &v1alpha1.IntegrationCloudwatch{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationCloudwatches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationcloudwatchesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationCloudwatchList{})
	return err
}

// Patch applies the patch and returns the patched integrationCloudwatch.
func (c *FakeIntegrationCloudwatches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationCloudwatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationcloudwatchesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationCloudwatch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudwatch), err
}
