/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationTeslas implements IntegrationTeslaInterface
type FakeIntegrationTeslas struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationteslasResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationteslas"}

var integrationteslasKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationTesla"}

// Get takes name of the integrationTesla, and returns the corresponding integrationTesla object, and an error if there is any.
func (c *FakeIntegrationTeslas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationTesla, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationteslasResource, c.ns, name), &v1alpha1.IntegrationTesla{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationTesla), err
}

// List takes label and field selectors, and returns the list of IntegrationTeslas that match those selectors.
func (c *FakeIntegrationTeslas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationTeslaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationteslasResource, integrationteslasKind, c.ns, opts), &v1alpha1.IntegrationTeslaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationTeslaList{ListMeta: obj.(*v1alpha1.IntegrationTeslaList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationTeslaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationTeslas.
func (c *FakeIntegrationTeslas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationteslasResource, c.ns, opts))

}

// Create takes the representation of a integrationTesla and creates it.  Returns the server's representation of the integrationTesla, and an error, if there is any.
func (c *FakeIntegrationTeslas) Create(ctx context.Context, integrationTesla *v1alpha1.IntegrationTesla, opts v1.CreateOptions) (result *v1alpha1.IntegrationTesla, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationteslasResource, c.ns, integrationTesla), &v1alpha1.IntegrationTesla{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationTesla), err
}

// Update takes the representation of a integrationTesla and updates it. Returns the server's representation of the integrationTesla, and an error, if there is any.
func (c *FakeIntegrationTeslas) Update(ctx context.Context, integrationTesla *v1alpha1.IntegrationTesla, opts v1.UpdateOptions) (result *v1alpha1.IntegrationTesla, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationteslasResource, c.ns, integrationTesla), &v1alpha1.IntegrationTesla{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationTesla), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationTeslas) UpdateStatus(ctx context.Context, integrationTesla *v1alpha1.IntegrationTesla, opts v1.UpdateOptions) (*v1alpha1.IntegrationTesla, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationteslasResource, "status", c.ns, integrationTesla), &v1alpha1.IntegrationTesla{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationTesla), err
}

// Delete takes name of the integrationTesla and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationTeslas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationteslasResource, c.ns, name), &v1alpha1.IntegrationTesla{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationTeslas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationteslasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationTeslaList{})
	return err
}

// Patch applies the patch and returns the patched integrationTesla.
func (c *FakeIntegrationTeslas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationTesla, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationteslasResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationTesla{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationTesla), err
}
