/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationNewrelics implements IntegrationNewrelicInterface
type FakeIntegrationNewrelics struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationnewrelicsResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationnewrelics"}

var integrationnewrelicsKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationNewrelic"}

// Get takes name of the integrationNewrelic, and returns the corresponding integrationNewrelic object, and an error if there is any.
func (c *FakeIntegrationNewrelics) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationnewrelicsResource, c.ns, name), &v1alpha1.IntegrationNewrelic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationNewrelic), err
}

// List takes label and field selectors, and returns the list of IntegrationNewrelics that match those selectors.
func (c *FakeIntegrationNewrelics) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationNewrelicList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationnewrelicsResource, integrationnewrelicsKind, c.ns, opts), &v1alpha1.IntegrationNewrelicList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationNewrelicList{ListMeta: obj.(*v1alpha1.IntegrationNewrelicList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationNewrelicList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationNewrelics.
func (c *FakeIntegrationNewrelics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationnewrelicsResource, c.ns, opts))

}

// Create takes the representation of a integrationNewrelic and creates it.  Returns the server's representation of the integrationNewrelic, and an error, if there is any.
func (c *FakeIntegrationNewrelics) Create(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.CreateOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationnewrelicsResource, c.ns, integrationNewrelic), &v1alpha1.IntegrationNewrelic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationNewrelic), err
}

// Update takes the representation of a integrationNewrelic and updates it. Returns the server's representation of the integrationNewrelic, and an error, if there is any.
func (c *FakeIntegrationNewrelics) Update(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (result *v1alpha1.IntegrationNewrelic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationnewrelicsResource, c.ns, integrationNewrelic), &v1alpha1.IntegrationNewrelic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationNewrelic), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationNewrelics) UpdateStatus(ctx context.Context, integrationNewrelic *v1alpha1.IntegrationNewrelic, opts v1.UpdateOptions) (*v1alpha1.IntegrationNewrelic, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationnewrelicsResource, "status", c.ns, integrationNewrelic), &v1alpha1.IntegrationNewrelic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationNewrelic), err
}

// Delete takes name of the integrationNewrelic and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationNewrelics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationnewrelicsResource, c.ns, name), &v1alpha1.IntegrationNewrelic{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationNewrelics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationnewrelicsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationNewrelicList{})
	return err
}

// Patch applies the patch and returns the patched integrationNewrelic.
func (c *FakeIntegrationNewrelics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationNewrelic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationnewrelicsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationNewrelic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationNewrelic), err
}
