/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationGcps implements IntegrationGcpInterface
type FakeIntegrationGcps struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationgcpsResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationgcps"}

var integrationgcpsKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationGcp"}

// Get takes name of the integrationGcp, and returns the corresponding integrationGcp object, and an error if there is any.
func (c *FakeIntegrationGcps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationGcp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationgcpsResource, c.ns, name), &v1alpha1.IntegrationGcp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcp), err
}

// List takes label and field selectors, and returns the list of IntegrationGcps that match those selectors.
func (c *FakeIntegrationGcps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationGcpList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationgcpsResource, integrationgcpsKind, c.ns, opts), &v1alpha1.IntegrationGcpList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationGcpList{ListMeta: obj.(*v1alpha1.IntegrationGcpList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationGcpList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationGcps.
func (c *FakeIntegrationGcps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationgcpsResource, c.ns, opts))

}

// Create takes the representation of a integrationGcp and creates it.  Returns the server's representation of the integrationGcp, and an error, if there is any.
func (c *FakeIntegrationGcps) Create(ctx context.Context, integrationGcp *v1alpha1.IntegrationGcp, opts v1.CreateOptions) (result *v1alpha1.IntegrationGcp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationgcpsResource, c.ns, integrationGcp), &v1alpha1.IntegrationGcp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcp), err
}

// Update takes the representation of a integrationGcp and updates it. Returns the server's representation of the integrationGcp, and an error, if there is any.
func (c *FakeIntegrationGcps) Update(ctx context.Context, integrationGcp *v1alpha1.IntegrationGcp, opts v1.UpdateOptions) (result *v1alpha1.IntegrationGcp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationgcpsResource, c.ns, integrationGcp), &v1alpha1.IntegrationGcp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcp), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationGcps) UpdateStatus(ctx context.Context, integrationGcp *v1alpha1.IntegrationGcp, opts v1.UpdateOptions) (*v1alpha1.IntegrationGcp, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationgcpsResource, "status", c.ns, integrationGcp), &v1alpha1.IntegrationGcp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcp), err
}

// Delete takes name of the integrationGcp and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationGcps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationgcpsResource, c.ns, name), &v1alpha1.IntegrationGcp{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationGcps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationgcpsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationGcpList{})
	return err
}

// Patch applies the patch and returns the patched integrationGcp.
func (c *FakeIntegrationGcps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationGcp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationgcpsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationGcp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcp), err
}
