/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationGcpBillings implements IntegrationGcpBillingInterface
type FakeIntegrationGcpBillings struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationgcpbillingsResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationgcpbillings"}

var integrationgcpbillingsKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationGcpBilling"}

// Get takes name of the integrationGcpBilling, and returns the corresponding integrationGcpBilling object, and an error if there is any.
func (c *FakeIntegrationGcpBillings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationgcpbillingsResource, c.ns, name), &v1alpha1.IntegrationGcpBilling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcpBilling), err
}

// List takes label and field selectors, and returns the list of IntegrationGcpBillings that match those selectors.
func (c *FakeIntegrationGcpBillings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationGcpBillingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationgcpbillingsResource, integrationgcpbillingsKind, c.ns, opts), &v1alpha1.IntegrationGcpBillingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationGcpBillingList{ListMeta: obj.(*v1alpha1.IntegrationGcpBillingList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationGcpBillingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationGcpBillings.
func (c *FakeIntegrationGcpBillings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationgcpbillingsResource, c.ns, opts))

}

// Create takes the representation of a integrationGcpBilling and creates it.  Returns the server's representation of the integrationGcpBilling, and an error, if there is any.
func (c *FakeIntegrationGcpBillings) Create(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.CreateOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationgcpbillingsResource, c.ns, integrationGcpBilling), &v1alpha1.IntegrationGcpBilling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcpBilling), err
}

// Update takes the representation of a integrationGcpBilling and updates it. Returns the server's representation of the integrationGcpBilling, and an error, if there is any.
func (c *FakeIntegrationGcpBillings) Update(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (result *v1alpha1.IntegrationGcpBilling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationgcpbillingsResource, c.ns, integrationGcpBilling), &v1alpha1.IntegrationGcpBilling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcpBilling), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationGcpBillings) UpdateStatus(ctx context.Context, integrationGcpBilling *v1alpha1.IntegrationGcpBilling, opts v1.UpdateOptions) (*v1alpha1.IntegrationGcpBilling, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationgcpbillingsResource, "status", c.ns, integrationGcpBilling), &v1alpha1.IntegrationGcpBilling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcpBilling), err
}

// Delete takes name of the integrationGcpBilling and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationGcpBillings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationgcpbillingsResource, c.ns, name), &v1alpha1.IntegrationGcpBilling{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationGcpBillings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationgcpbillingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationGcpBillingList{})
	return err
}

// Patch applies the patch and returns the patched integrationGcpBilling.
func (c *FakeIntegrationGcpBillings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationGcpBilling, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationgcpbillingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationGcpBilling{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationGcpBilling), err
}
