/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationAwsExternalIDs implements IntegrationAwsExternalIDInterface
type FakeIntegrationAwsExternalIDs struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationawsexternalidsResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationawsexternalids"}

var integrationawsexternalidsKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationAwsExternalID"}

// Get takes name of the integrationAwsExternalID, and returns the corresponding integrationAwsExternalID object, and an error if there is any.
func (c *FakeIntegrationAwsExternalIDs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationAwsExternalID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationawsexternalidsResource, c.ns, name), &v1alpha1.IntegrationAwsExternalID{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationAwsExternalID), err
}

// List takes label and field selectors, and returns the list of IntegrationAwsExternalIDs that match those selectors.
func (c *FakeIntegrationAwsExternalIDs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationAwsExternalIDList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationawsexternalidsResource, integrationawsexternalidsKind, c.ns, opts), &v1alpha1.IntegrationAwsExternalIDList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationAwsExternalIDList{ListMeta: obj.(*v1alpha1.IntegrationAwsExternalIDList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationAwsExternalIDList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationAwsExternalIDs.
func (c *FakeIntegrationAwsExternalIDs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationawsexternalidsResource, c.ns, opts))

}

// Create takes the representation of a integrationAwsExternalID and creates it.  Returns the server's representation of the integrationAwsExternalID, and an error, if there is any.
func (c *FakeIntegrationAwsExternalIDs) Create(ctx context.Context, integrationAwsExternalID *v1alpha1.IntegrationAwsExternalID, opts v1.CreateOptions) (result *v1alpha1.IntegrationAwsExternalID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationawsexternalidsResource, c.ns, integrationAwsExternalID), &v1alpha1.IntegrationAwsExternalID{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationAwsExternalID), err
}

// Update takes the representation of a integrationAwsExternalID and updates it. Returns the server's representation of the integrationAwsExternalID, and an error, if there is any.
func (c *FakeIntegrationAwsExternalIDs) Update(ctx context.Context, integrationAwsExternalID *v1alpha1.IntegrationAwsExternalID, opts v1.UpdateOptions) (result *v1alpha1.IntegrationAwsExternalID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationawsexternalidsResource, c.ns, integrationAwsExternalID), &v1alpha1.IntegrationAwsExternalID{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationAwsExternalID), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationAwsExternalIDs) UpdateStatus(ctx context.Context, integrationAwsExternalID *v1alpha1.IntegrationAwsExternalID, opts v1.UpdateOptions) (*v1alpha1.IntegrationAwsExternalID, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationawsexternalidsResource, "status", c.ns, integrationAwsExternalID), &v1alpha1.IntegrationAwsExternalID{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationAwsExternalID), err
}

// Delete takes name of the integrationAwsExternalID and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationAwsExternalIDs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationawsexternalidsResource, c.ns, name), &v1alpha1.IntegrationAwsExternalID{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationAwsExternalIDs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationawsexternalidsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationAwsExternalIDList{})
	return err
}

// Patch applies the patch and returns the patched integrationAwsExternalID.
func (c *FakeIntegrationAwsExternalIDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationAwsExternalID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationawsexternalidsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationAwsExternalID{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationAwsExternalID), err
}
