/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationCloudtrails implements IntegrationCloudtrailInterface
type FakeIntegrationCloudtrails struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var integrationcloudtrailsResource = schema.GroupVersionResource{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Resource: "integrationcloudtrails"}

var integrationcloudtrailsKind = schema.GroupVersionKind{Group: "cloud.wavefront.kubeform.com", Version: "v1alpha1", Kind: "IntegrationCloudtrail"}

// Get takes name of the integrationCloudtrail, and returns the corresponding integrationCloudtrail object, and an error if there is any.
func (c *FakeIntegrationCloudtrails) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationcloudtrailsResource, c.ns, name), &v1alpha1.IntegrationCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudtrail), err
}

// List takes label and field selectors, and returns the list of IntegrationCloudtrails that match those selectors.
func (c *FakeIntegrationCloudtrails) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationCloudtrailList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationcloudtrailsResource, integrationcloudtrailsKind, c.ns, opts), &v1alpha1.IntegrationCloudtrailList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationCloudtrailList{ListMeta: obj.(*v1alpha1.IntegrationCloudtrailList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationCloudtrailList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationCloudtrails.
func (c *FakeIntegrationCloudtrails) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationcloudtrailsResource, c.ns, opts))

}

// Create takes the representation of a integrationCloudtrail and creates it.  Returns the server's representation of the integrationCloudtrail, and an error, if there is any.
func (c *FakeIntegrationCloudtrails) Create(ctx context.Context, integrationCloudtrail *v1alpha1.IntegrationCloudtrail, opts v1.CreateOptions) (result *v1alpha1.IntegrationCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationcloudtrailsResource, c.ns, integrationCloudtrail), &v1alpha1.IntegrationCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudtrail), err
}

// Update takes the representation of a integrationCloudtrail and updates it. Returns the server's representation of the integrationCloudtrail, and an error, if there is any.
func (c *FakeIntegrationCloudtrails) Update(ctx context.Context, integrationCloudtrail *v1alpha1.IntegrationCloudtrail, opts v1.UpdateOptions) (result *v1alpha1.IntegrationCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationcloudtrailsResource, c.ns, integrationCloudtrail), &v1alpha1.IntegrationCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudtrail), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationCloudtrails) UpdateStatus(ctx context.Context, integrationCloudtrail *v1alpha1.IntegrationCloudtrail, opts v1.UpdateOptions) (*v1alpha1.IntegrationCloudtrail, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationcloudtrailsResource, "status", c.ns, integrationCloudtrail), &v1alpha1.IntegrationCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudtrail), err
}

// Delete takes name of the integrationCloudtrail and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationCloudtrails) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationcloudtrailsResource, c.ns, name), &v1alpha1.IntegrationCloudtrail{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationCloudtrails) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationcloudtrailsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationCloudtrailList{})
	return err
}

// Patch applies the patch and returns the patched integrationCloudtrail.
func (c *FakeIntegrationCloudtrails) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationcloudtrailsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationCloudtrail), err
}
