/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "kubeform.dev/provider-wavefront-api/client/clientset/versioned"
	alertv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/alert/v1alpha1"
	fakealertv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/alert/v1alpha1/fake"
	cloudv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/cloud/v1alpha1"
	fakecloudv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/cloud/v1alpha1/fake"
	dashboardv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/dashboard/v1alpha1"
	fakedashboardv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/dashboard/v1alpha1/fake"
	derivedv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/derived/v1alpha1"
	fakederivedv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/derived/v1alpha1/fake"
	externalv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/external/v1alpha1"
	fakeexternalv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/external/v1alpha1/fake"
	ingestionv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/ingestion/v1alpha1"
	fakeingestionv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/ingestion/v1alpha1/fake"
	maintenancev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/maintenance/v1alpha1"
	fakemaintenancev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/maintenance/v1alpha1/fake"
	rolev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/role/v1alpha1"
	fakerolev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/role/v1alpha1/fake"
	servicev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/service/v1alpha1"
	fakeservicev1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/service/v1alpha1/fake"
	userv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/user/v1alpha1"
	fakeuserv1alpha1 "kubeform.dev/provider-wavefront-api/client/clientset/versioned/typed/user/v1alpha1/fake"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// AlertV1alpha1 retrieves the AlertV1alpha1Client
func (c *Clientset) AlertV1alpha1() alertv1alpha1.AlertV1alpha1Interface {
	return &fakealertv1alpha1.FakeAlertV1alpha1{Fake: &c.Fake}
}

// CloudV1alpha1 retrieves the CloudV1alpha1Client
func (c *Clientset) CloudV1alpha1() cloudv1alpha1.CloudV1alpha1Interface {
	return &fakecloudv1alpha1.FakeCloudV1alpha1{Fake: &c.Fake}
}

// DashboardV1alpha1 retrieves the DashboardV1alpha1Client
func (c *Clientset) DashboardV1alpha1() dashboardv1alpha1.DashboardV1alpha1Interface {
	return &fakedashboardv1alpha1.FakeDashboardV1alpha1{Fake: &c.Fake}
}

// DerivedV1alpha1 retrieves the DerivedV1alpha1Client
func (c *Clientset) DerivedV1alpha1() derivedv1alpha1.DerivedV1alpha1Interface {
	return &fakederivedv1alpha1.FakeDerivedV1alpha1{Fake: &c.Fake}
}

// ExternalV1alpha1 retrieves the ExternalV1alpha1Client
func (c *Clientset) ExternalV1alpha1() externalv1alpha1.ExternalV1alpha1Interface {
	return &fakeexternalv1alpha1.FakeExternalV1alpha1{Fake: &c.Fake}
}

// IngestionV1alpha1 retrieves the IngestionV1alpha1Client
func (c *Clientset) IngestionV1alpha1() ingestionv1alpha1.IngestionV1alpha1Interface {
	return &fakeingestionv1alpha1.FakeIngestionV1alpha1{Fake: &c.Fake}
}

// MaintenanceV1alpha1 retrieves the MaintenanceV1alpha1Client
func (c *Clientset) MaintenanceV1alpha1() maintenancev1alpha1.MaintenanceV1alpha1Interface {
	return &fakemaintenancev1alpha1.FakeMaintenanceV1alpha1{Fake: &c.Fake}
}

// RoleV1alpha1 retrieves the RoleV1alpha1Client
func (c *Clientset) RoleV1alpha1() rolev1alpha1.RoleV1alpha1Interface {
	return &fakerolev1alpha1.FakeRoleV1alpha1{Fake: &c.Fake}
}

// ServiceV1alpha1 retrieves the ServiceV1alpha1Client
func (c *Clientset) ServiceV1alpha1() servicev1alpha1.ServiceV1alpha1Interface {
	return &fakeservicev1alpha1.FakeServiceV1alpha1{Fake: &c.Fake}
}

// UserV1alpha1 retrieves the UserV1alpha1Client
func (c *Clientset) UserV1alpha1() userv1alpha1.UserV1alpha1Interface {
	return &fakeuserv1alpha1.FakeUserV1alpha1{Fake: &c.Fake}
}
