/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubeform.dev/provider-wavefront-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// IntegrationAppDynamicses returns a IntegrationAppDynamicsInformer.
	IntegrationAppDynamicses() IntegrationAppDynamicsInformer
	// IntegrationAwsExternalIDs returns a IntegrationAwsExternalIDInformer.
	IntegrationAwsExternalIDs() IntegrationAwsExternalIDInformer
	// IntegrationAzures returns a IntegrationAzureInformer.
	IntegrationAzures() IntegrationAzureInformer
	// IntegrationAzureActivityLogs returns a IntegrationAzureActivityLogInformer.
	IntegrationAzureActivityLogs() IntegrationAzureActivityLogInformer
	// IntegrationCloudtrails returns a IntegrationCloudtrailInformer.
	IntegrationCloudtrails() IntegrationCloudtrailInformer
	// IntegrationCloudwatches returns a IntegrationCloudwatchInformer.
	IntegrationCloudwatches() IntegrationCloudwatchInformer
	// IntegrationEc2s returns a IntegrationEc2Informer.
	IntegrationEc2s() IntegrationEc2Informer
	// IntegrationGcps returns a IntegrationGcpInformer.
	IntegrationGcps() IntegrationGcpInformer
	// IntegrationGcpBillings returns a IntegrationGcpBillingInformer.
	IntegrationGcpBillings() IntegrationGcpBillingInformer
	// IntegrationNewrelics returns a IntegrationNewrelicInformer.
	IntegrationNewrelics() IntegrationNewrelicInformer
	// IntegrationTeslas returns a IntegrationTeslaInformer.
	IntegrationTeslas() IntegrationTeslaInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// IntegrationAppDynamicses returns a IntegrationAppDynamicsInformer.
func (v *version) IntegrationAppDynamicses() IntegrationAppDynamicsInformer {
	return &integrationAppDynamicsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationAwsExternalIDs returns a IntegrationAwsExternalIDInformer.
func (v *version) IntegrationAwsExternalIDs() IntegrationAwsExternalIDInformer {
	return &integrationAwsExternalIDInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationAzures returns a IntegrationAzureInformer.
func (v *version) IntegrationAzures() IntegrationAzureInformer {
	return &integrationAzureInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationAzureActivityLogs returns a IntegrationAzureActivityLogInformer.
func (v *version) IntegrationAzureActivityLogs() IntegrationAzureActivityLogInformer {
	return &integrationAzureActivityLogInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationCloudtrails returns a IntegrationCloudtrailInformer.
func (v *version) IntegrationCloudtrails() IntegrationCloudtrailInformer {
	return &integrationCloudtrailInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationCloudwatches returns a IntegrationCloudwatchInformer.
func (v *version) IntegrationCloudwatches() IntegrationCloudwatchInformer {
	return &integrationCloudwatchInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationEc2s returns a IntegrationEc2Informer.
func (v *version) IntegrationEc2s() IntegrationEc2Informer {
	return &integrationEc2Informer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationGcps returns a IntegrationGcpInformer.
func (v *version) IntegrationGcps() IntegrationGcpInformer {
	return &integrationGcpInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationGcpBillings returns a IntegrationGcpBillingInformer.
func (v *version) IntegrationGcpBillings() IntegrationGcpBillingInformer {
	return &integrationGcpBillingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationNewrelics returns a IntegrationNewrelicInformer.
func (v *version) IntegrationNewrelics() IntegrationNewrelicInformer {
	return &integrationNewrelicInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IntegrationTeslas returns a IntegrationTeslaInformer.
func (v *version) IntegrationTeslas() IntegrationTeslaInformer {
	return &integrationTeslaInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
