/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cloudv1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	versioned "kubeform.dev/provider-wavefront-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-wavefront-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-wavefront-api/client/listers/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IntegrationAzureInformer provides access to a shared informer and lister for
// IntegrationAzures.
type IntegrationAzureInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IntegrationAzureLister
}

type integrationAzureInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIntegrationAzureInformer constructs a new informer for IntegrationAzure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIntegrationAzureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIntegrationAzureInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIntegrationAzureInformer constructs a new informer for IntegrationAzure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIntegrationAzureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().IntegrationAzures(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().IntegrationAzures(namespace).Watch(context.TODO(), options)
			},
		},
		&cloudv1alpha1.IntegrationAzure{},
		resyncPeriod,
		indexers,
	)
}

func (f *integrationAzureInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIntegrationAzureInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *integrationAzureInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudv1alpha1.IntegrationAzure{}, f.defaultInformer)
}

func (f *integrationAzureInformer) Lister() v1alpha1.IntegrationAzureLister {
	return v1alpha1.NewIntegrationAzureLister(f.Informer().GetIndexer())
}
